### ISSUE TITLE
Control dx12 won't launch with latest GE7-21 vkd3d pull

### ISSUE THREAD

**Issue by jhu54** [HansKristian-Work/vkd3d-proton#1142]
Installed latest GE_Proton7-21 which includes VKD3D git pull from June 26. Using Epic Games (launched through Steam), Hitman 3 runs perfectly but Control dx12 fails to launch. Moving the d3d12.dll (git pull and compile from GE7-20, May 30th) into the correct folder for GE7-21 and Control launches and runs.

Seems something in the commits between these 2 dates has affected the launching of Control.

**Comment by K0bin** [comment]
Which graphics driver and version are you using?

**Comment by jhu54** [comment]
Sorry - 

> System:
  Host: GGI-LinuxMint Kernel: 5.18.7-tkg-bmq x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 5.2.7 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una 
  base: Ubuntu 20.04 focal 
CPU:
  Topology: 6-Core model: 11th Gen Intel Core i5-11600K 
Graphics:
  Device-1: AMD vendor: Tul driver: amdgpu v: kernel bus ID: 03:00.0 
  chip ID: 1002:73df 
  Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa resolution: 2560x1440~60Hz 
  OpenGL: renderer: AMD Radeon RX 6700 XT (navi22 LLVM 14.0.5 DRM 3.46 
  5.18.7-tkg-bmq) 
  v: 4.6 Mesa 22.2.0-devel (git-e8fc5cc 2022-06-22 focal-oibaf-ppa) 
  direct render: Yes

**Comment by K0bin** [comment]
>  Mesa 22.2.0-devel 

Okay, that's what I wanted to check. That's not the issue then.

**Comment by K0bin** [comment]
> Good thing is RayTracing works in World of Warcraft with the latest GIT and Mesa, bad news is FPS tanks by 70% (vs 20-30% on Win 10)...

Ray tracing in RADV is in a pretty early state and not optimized at all.

**Comment by jhu54** [comment]
Yep been playing with it from day 1 on RADV - not that I use it in games, but still fun to watch the tech and capability evolve...

**Comment by tizzir** [comment]
I can replicate the issue by using GE-Proton7-21 on Nvidia hardware. Game immediately quits before a window even appears, using the Steam version of Control. Using GE-Proton7-22, a black window opens for a second before closing.

I'm not so sure it's a VKD3D-Proton issue though, because building VKD3D-Proton from the `master` branch (commit [707af81](https://github.com/HansKristian-Work/vkd3d-proton/commit/707af8152e8be2d180ae2c20bf9d08530e92005f)) and using that with Proton Experimental has Control working just fine.

**Comment by tizzir** [comment]
Using the version of VKD3D-Proton `master` branch that I compiled myself with GE-Proton7-22 also seems to avoid the crash on startup.

**Comment by Iglu47** [comment]
at least on nvidia, Control EGS-version should starts fine on https://github.com/HansKristian-Work/vkd3d-proton/commit/707af8152e8be2d180ae2c20bf9d08530e92005f

<details><summary>some details</summary>
<p>

[vkd3d_proton.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8996085/vkd3d_proton.log)
```
System:
  Host: home-pc Kernel: 5.15.44-custom x86_64 bits: 64 compiler: N/A 
  Desktop: Cinnamon 5.4.2 dm: LightDM Distro: Arch Linux 
Machine:
  Type: Desktop System: ASUS product: All Series v: N/A 
  serial: <root required> 
  Mobo: ASUSTeK model: MAXIMUS VII HERO v: Rev 1.xx serial: <root required> 
  UEFI: American Megatrends v: 3201 date: 01/24/2017 
Graphics:
  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] vendor: Gigabyte 
  driver: nvidia v: 515.48.07 bus ID: 01:00.0 chip ID: 10de:1b06 
  Display: server: X.Org 21.1.3 driver: nvidia resolution: 1920x1080~60Hz 
  OpenGL: renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 
  v: 4.6.0 NVIDIA 515.48.07 direct render: Yes 
```
![control_egs_dx12](https://user-images.githubusercontent.com/25866099/176050126-29dbb698-78c8-45ef-97ba-109aa5d12af1.png)

</p>
</details>
