### ISSUE TITLE
Cyberpunk 2077 is spamming d3d12_fence_signal_external_events_locked

### ISSUE THREAD

**Issue by shmerl** [HansKristian-Work/vkd3d-proton#1309]
I noticed that Cyberpunk 2077 is spamming this in the log:

```
01dc:err:d3d12_fence_signal_external_events_locked: Failed to signal event, hr #80004005.
01dc:err:d3d12_fence_signal_external_events_locked: Failed to signal event, hr #80004005.
```

Using it with radv and such settings enabled (Mesa main, kernel 6.1-rc6+ with patches that prevent the game from crashing):

```
export RADV_PERFTEST='rt,gpl,ext_ms'
export VKD3D_CONFIG='dxr11'
```

**Comment by HansKristian-Work** [comment]
Does this only repro with DXR enabled? Does this repro on latest master? I only get warning spam about swapchain latency fences, but that's a known game issue.

**Comment by shmerl** [comment]
I just tried with those variables unset (so dxr not overriden and radv ray tracing not enabled), and these errors still spam the log.

Current vkd3d-proton master, Mesa main, kernel 6.1-rc7.

**Comment by HansKristian-Work** [comment]
> with cyberengine tweaks enabled

What about plain 1.61?

**Comment by shmerl** [comment]
OK, I tried removing the plug, overrides for `version` and set `d3dcompiler_47` to builtin. It's still spamming those errors.

**Comment by shmerl** [comment]
Hm, I should have added more info on my set up - I'm using upstream Wine 7.22 with vkd3d-proton added in the prefix.

**Comment by kostadin04** [comment]
Same spam on Proton Experimental(bleeding-edge), no cyberengine tweaks, no raytracing enabled, only using `RADV_PERFTEST=sam` rx 6800, mesa-git, 6.0.10 kernel
[vkd3d-proton.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10143399/vkd3d-proton.log)

**Comment by shmerl** [comment]
Btw, didn't `RADV_PERFTEST=sam` became the default now? I think I've seen something about it.

**Comment by TURING-V2** [comment]
happens on 1650ti also, lutris wine -ge & tkg no dxr,  game ver 1.61 no mod

**Comment by HansKristian-Work** [comment]
I still cannot reproduce this. With warn logging on, I get:

```
0228:warn:vkd3d_native_sync_handle_release: Failed to release semaphore (#12a).
0228:warn:dxgi_vk_swap_chain_wait_worker: Failed to increment swapchain semaphore. Did application forget to acquire?
0148:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0158:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0158:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0228:warn:vkd3d_native_sync_handle_release: Failed to release semaphore (#12a).
0228:warn:dxgi_vk_swap_chain_wait_worker: Failed to increment swapchain semaphore. Did application forget to acquire?
0138:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0138:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0138:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0228:warn:vkd3d_native_sync_handle_release: Failed to release semaphore (#12a).
0228:warn:dxgi_vk_swap_chain_wait_worker: Failed to increment swapchain semaphore. Did application forget to acquire?
0144:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0140:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0140:warn:d3d12_command_list_OMSetRenderTargets: RTV descriptor 1 is not initialized.
0228:warn:vkd3d_native_sync_handle_release: Failed to release semaphore (#12a).
```
These warnings as expected at least.

**Comment by kostadin04** [comment]
I have everything on max except Screen Space Reflections Quality, which is on high and everything in "Basic" is off and FOV is set to 90, 1080p. Also, it looks like it appears with err enabled in the logging, not just warn.

**Comment by shmerl** [comment]
Still happens with latest master. Message that's being spammed mostly is this:

```
0188:err:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
0188:err:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
0188:err:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
```

**Comment by shmerl** [comment]
I'm still getting this spammed:

```
78793.225:0020:01ac:err:vkd3d-proton:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
78793.229:0020:01ac:err:vkd3d-proton:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
78793.235:0020:01ac:err:vkd3d-proton:vkd3d_waiting_event_signal: Failed to signal event, hr #80004005.
```

**Comment by qarmin** [comment]
Same problem with vkd3d-proton b7fb41b running on Bottles, but I run game on almost lowest settings
```
System:
   Kernel: 5.19.0-31-generic arch: x86_64 bits: 64
    compiler: N/A Desktop: GNOME v: 43.1 Distro: Ubuntu 22.10 (Kinetic Kudu)
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    vendor: Sapphire driver: amdgpu v: kernel arch: GCN-4 bus-ID: 01:00.0
  Display: x11 server: X.Org v: 1.21.1.4 with: Xwayland v: 22.1.3 driver:
    X: loaded: amdgpu unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon RX 570 Series (polaris10 LLVM 15.0.7 DRM
    3.47 5.19.0-31-generic) v: 4.6 Mesa 22.3.5 (git-78ef633056)
    direct render: Yes
```
